language: cpp
script: "cmake -G 'Unix Makefiles' && make"
compiler: gcc

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install libboost-all-dev libssl-dev xorg-dev
    - git clone --depth 5 https://github.com/glfw/glfw.git
    - cd glfw
    - "cmake -G 'Unix Makefiles' && make && sudo make install"
    - cd ..

notifications:
    irc:
        channels:
            - "irc.freenode.net#tridevs"
            - "irc.freenode.net#crappycraft"
        on_success: always
        on_failure: always
